apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mongodb
  template:
    metadata:
      labels:
        db: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
       
