apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: ariyeb/k8s-net-users:latest
        env:
          - name: PORT
            value: "8000"
          - name: AUTH_ADDRESS
            value: "auth-service.default:4000"
