apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mysql
  template:
    metadata:
      labels:
        db: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "root321"
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mysql-env
                key: MYSQL_DATABASE