version: "3.9"

services:
  redis:
    image: redis
  mongodb:
    image: mongo
  auth:
    build: ./auth
    ports:
      - 4000:4000
    env_file:
      - ./auth/config/dev.env
    depends_on:
      - redis
  users:
    build: ./users
    ports:
      - 8000:8000
    env_file:
      - ./users/config/dev.env
    depends_on:
      - mongodb
      - auth
  messages:
    build: ./messages
    ports:
      - 8080:8080
    env_file:
      - ./messages/config/dev.env
    depends_on:
      - mongodb
      - auth
      - users
  front:
    build: ./front
    ports:
      - 3000:3000
    depends_on:
      - messages
