apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volumes-pvc
spec:
  volumeName: volumes-pv
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
